### ISSUE TITLE
Issue and Request

### ISSUE THREAD

**Issue by AlreadyGotcha** [Fleeym/jukebox#11]
I got crashed while adding NONGs:
[2024-02-03_17-57-59.log](https://github.com/Fleeym/jukebox/files/14151166/2024-02-03_17-57-59.log)
and also give use back the fletching id song feature.

**Comment by Fleeym** [comment]
Give media permissions to the Geode app in your phone settings

**Comment by nauqi-1** [comment]
I've the same problem, crashing while adding NONGs.

I gave Geode storage permissions on my phone, this is what it looks like:
![Screenshot_2024-02-05-11-36-55-22](https://github.com/Fleeym/jukebox/assets/158802504/9acdd109-eddc-426a-b6f0-e4053e6e16c6)

Crashlog:
[0f49cbed-5ecd-4658-34456fb2-c78bcd3c.dmp](https://github.com/Fleeym/jukebox/files/14160628/0f49cbed-5ecd-4658-34456fb2-c78bcd3c.dmp)

(I can still add NONGs by directly copying the mp3 to the Geode data folder tho so no biggie )

**Comment by Fleeym** [comment]
problem should be gone now with the latest version, please try it
