### ISSUE TITLE
Unable to load the DLL: ERROR_PROC_NOT_FOUND

### ISSUE THREAD

**Issue by thepwrtank18** [Fleeym/jukebox#12]
![A textbox containing the header "Problem Info", and the text "Unable to load the DLL: ERROR_PROC_NOT_FOUND; The mod tried to access a function defined in another DLL, but the specified function was not found. Make sure the other DLL exports the given symbol, and that it is defined in the DLL. If you are not the developer of this mod, report this error to them as it is likely not your fault."](https://github.com/Fleeym/jukebox/assets/57580668/8c23c3b7-b6e6-40fb-aded-da48013d5503)

**Comment by TheSeverus** [comment]
![imagen_2024-02-03_211759272](https://github.com/Fleeym/jukebox/assets/158790359/24f85676-07e2-4cb6-b657-857a843a272c)

**Comment by TheSeverus** [comment]
Please Help

**Comment by RueOfficial** [comment]
Have the same issue here

**Comment by Androphonomania** [comment]
![image](https://github.com/Fleeym/jukebox/assets/88868724/5be0bbf5-23ec-4b59-bdb2-571de7025d25)
same

**Comment by TheSeverus** [comment]
we will have to wait

**Comment by RueOfficial** [comment]
Everyone! i found what the issue is!

You will need to manually update Geode to Beta 14 to fix the issue, the auto update doesnt work for IOS and Windows iirc

**Comment by TheSeverus** [comment]
ohh ok ok thank you!

**Comment by Fleeym** [comment]
Yep, auto updater broke in beta.12, sorry for not responding!
