### ISSUE TITLE
Error : You need to allow media permissions to import songs

### ISSUE THREAD

**Issue by Imamongus-sus** [Fleeym/jukebox#13]
I allowed the media permissions and it still occurred

**Comment by nauqi-1** [comment]
Same here, there's no pop-up asking for media access permission.

**Comment by GDHopping** [comment]
Same here, tried putting in a nong and this happened. And yes I do have permissions on
BTW this is happening on Android
![Screenshot_20240204-075351_Geode](https://github.com/Fleeym/jukebox/assets/158805892/d5672a13-4f08-4558-adc5-9e37c6cab9a2)

**Comment by Fleeym** [comment]
I removed the permission check in the latest version, should be fine now
