### ISSUE TITLE
Geode mod failed loading

### ISSUE THREAD

**Issue by Whiskers11** [Fleeym/jukebox#16]
As said, with the new update, Jukebox has failed to load. 
![image](https://github.com/Fleeym/jukebox/assets/158112176/1121c4fc-2924-4ed1-8a3d-e7f705d662b9)
(plz image work)

**Comment by EMREOYUN** [comment]
In android, it just crashes the entire Geode

**Comment by Fleeym** [comment]
update geode manually, the auto updater broke

**Comment by necocat0918** [comment]
still not working, I'm on the latest Geode version
