### ISSUE TITLE
Unknown song

### ISSUE THREAD

**Issue by PryzhokNaRobote** [Fleeym/jukebox#17]
![Screenshot_2024-02-05-22-39-35-25_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/Fleeym/jukebox/assets/156057628/382df4b0-6f4c-42fd-af6a-b6d7c90166b6)
I want to use nong song, but I can't choose it in "saved" folder

**Comment by Fleeym** [comment]
enter any level and click on the song name

**Comment by Fleeym** [comment]
also update jukebox, I added a fix that should remove the unknown bug
