### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Helloausername** [Fleeym/jukebox#20]
Make it possible to replace robtop songs

**Comment by Fleeym** [comment]
Its a bit more complicated, I'll try to implement it in the future.

**Comment by RoootTheFox** [comment]
couldn't you just do [what `textureldr` does](https://github.com/geode-sdk/textureldr/blob/4ca6cd704b279cb11c0c223e4ebce06eaf97f154/src/Pack.cpp#L64) for resource packs (or perhaps hooking the function that loads the songs, checking if its the main song you want to modify and then returning the modified version)?

that's just a silly idea, i don't actually know how viable this is.

**Comment by Helloausername** [comment]
when I tried to put like a texture pack it didn't work

**Comment by RoootTheFox** [comment]
then I'd assume songs aren't loaded through cocos(?), would have to do some reverse engineering to know for sure though.

**Comment by Fleeym** [comment]
Implemented a while ago, closing this.
