### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Helloausername** [Fleeym/jukebox#27]
theres a chance to crash on mobile when entering song name or artist name

android 32bit

[Crash 2024-03-21 12.23.23.dmp](https://github.com/Fleeym/jukebox/files/14693603/Crash.2024-03-21.12.23.23.dmp)
[Crash 2024-03-21 12.23.00.dmp](https://github.com/Fleeym/jukebox/files/14693605/Crash.2024-03-21.12.23.00.dmp)
[Crash 2024-03-21 12.19.25.dmp](https://github.com/Fleeym/jukebox/files/14693606/Crash.2024-03-21.12.19.25.dmp)

**Comment by Fleeym** [comment]
Try moving the file you import in the downloads folder.
