### ISSUE TITLE
Crash (happened when loading a Daily level with the already known 'Unknown' song bug that exists in Vanilla)

### ISSUE THREAD

**Issue by cretaceous-rexd** [Fleeym/jukebox#31]
It looked like this:

![20240411005724_1](https://github.com/Fleeym/jukebox/assets/62309753/4994d833-4971-4166-819f-8c4d6df022a9)

Then when I pressed the 'play' button, the game immediately crashed with this log:

[2024-04-11_00-57-31.log](https://github.com/Fleeym/jukebox/files/14939019/2024-04-11_00-57-31.log)

**Comment by Fleeym** [comment]
I'm working on a fix, should be out some time today, sorry for the issues
