### ISSUE TITLE
Game Crashes When Song ID Has Newgrounds Song

### ISSUE THREAD

**Issue by ukkn0wn** [Fleeym/jukebox#32]
Many levels use song IDs with no NG song attached, when Jukebox is enabled, these levels crash when exiting or clicking on the options menu in the editor.
![image](https://github.com/Fleeym/jukebox/assets/97061371/c451095f-03a2-403e-a8c9-1e5ec7f900fc)

**Comment by Fleeym** [comment]
I'm gonna close this because it's old. If it still happens please reopen, and also include a crashlog.
