### ISSUE TITLE
[bug] Completely doesn't work for me

### ISSUE THREAD

**Issue by ElectroMuffin** [Fleeym/jukebox#34]
I do all of the steps needed (go to the song menu, click the plus button, set the name and the location of the file, click "set" on the newly added nong...) and it's just complete silence

**Comment by Fleeym** [comment]
what platform are you on?

**Comment by ElectroMuffin** [comment]
> what platform are you on?

Windows/Geode (srry for late reply)

**Comment by Fleeym** [comment]
do you have any odd characters in your windows username? (é, russian characters, etc)

**Comment by ElectroMuffin** [comment]
> do you have any odd characters in your windows username? (é, russian characters, etc)

nope, only regular letters, also the mod works, but the songs just not there (yes the song file is notblank i checked)

**Comment by Didisla** [comment]
having the same issue. I do have non-ASCII letters in my windows username, however, the path to the folder with my NONGs looks like this:
E:\nongs
so I don't think that's the problem.

**Comment by Fleeym** [comment]
Jukebox moves the songs to a special folder, that is under your user dir. I'll look into adding custom song storage locations

**Comment by Fleeym** [comment]
This should be fixed now
