### ISSUE TITLE
What happened to SFH compatibility?  

### ISSUE THREAD

**Issue by Whiskers11** [Fleeym/jukebox#4]
When ever I try changing my NONG it says "Failed to set song: file not found," and when I try finding new NONG's it just brings me to https://songfilehub.com/home. What happened?

**Comment by Fleeym** [comment]
song file hub support was dropped in the last update, you can check this release out for more info
https://github.com/Fleeym/jukebox/releases/tag/v2.2.0

**Comment by PmikeGamer** [comment]
the whole point i got this mod is GONE now

**Comment by Fleeym** [comment]
it is what it is

**Comment by whitemaskedwolf** [comment]
soo did you just straight up erase the entire git tree up to the update which removed song file hub integration?

people downloading all of the applicable songs from the song file hub manually is ultimately going to have the same impact on the servers as the mod doing it automatically, so i don't even see the reason to remove the functionality in the first place, let alone undermine version control to prevent people from gaining access to previous versions of the mod.

**Comment by Fleeym** [comment]
the difference here is convenience. it was much more convenient to just click set on different songs you had fetched compared to downloading each one in particular and checking it out. also the website has ads, those balance out expenses a little
i myself am not sure if that sudden jump of usage was because of jukebox, but it surely did align with its increase in popularity, especially among android players. for now, i think i did the right thing. if we figure out a solution, i would be glad to bring back the integration :)

**Comment by RoootTheFox** [comment]
hi @Fleeym, sorry for "hijacking" this issue. I would be willing to host a mirror of all songs on SFH, including an API for mods like Jukebox.

I would also be willing to work together with the SFH team to make the mirror/API as seamless as possible.

My current plan/idea consists of a small web service, that:
- periodically monitors SFH for changes
  - (every hour or so, maybe even through a webhook or similar to make updating songs faster)
- saves the songs
- and provides an API for integrations like Jukebox.

I already have a server (VPS), so hosting wouldn't be an issue for me.

That way this mod would no longer stress out SFH's servers, while being able to retain the convenient in-game NONG downloading function that everyone misses.

Is this something you'd be willing to implement?

**Comment by Fleeym** [comment]
Sure, the main problem that SFH encountered was outbound traffic limits. Jukebox took about 600GB / 4 days, and their monthly limit was about 6TB. Obviously, Jukebox's consumption rate would only increase as time goes on. Do keep this in mind when going through with your idea.

**Comment by RoootTheFox** [comment]
Okay, that *is* a lot of data (and now I fully understand why you dropped SFH compatibility)
My server has an outgoing traffic limit of 32TB(/month?) so I don't think traffic limits are an issue (I don't think bandwidth will be problematic either; if my calculations are correct it should average out to about 2MB/s, although this will obviously be *way* higher during peak hours)

I have two other ideas:
- (relatively no-brainer to me): CloudFlare CDN/proxying the actual song files, I'm pretty sure even the CF free tier could make a pretty huge difference here
- a different server architecture that works like this:
  - Jukebox -> main API/load distributor (selects a mirror based on server load or RNG, returns URL for the song on that mirror) -> Jukebox (requests the song from that specific mirror)
  - That way, hosting of songs can be more decentralized, reduce load on individual mirrors and mitigate downtime if a mirror goes offline for a bit
  - (There could obviously be multiple load balancers run by different people too, that way load balancer downtime could be mitigated as well)
   - That way, people with the necessary server infrastructure that want to help out can volunteer to host both mirrors (where the actual song files are saved) and optionally load distributors for higher reliability, allowing easy scaling and therefore making everything more future-proof.

**Comment by Fleeym** [comment]
I think just CloudFlare should improve things by quite a lot. I'm sure it can also cache stuff a little more aggressively, since the files don't really change. That should be a good enough start.

**Comment by RoootTheFox** [comment]
@Fleeym i made an initial version of the mirror API server, source code can be found [here](https://github.com/RoootTheFox/sfh-mirror) (I'll do proper error handling tomorrow, as well as setup documentation)

The API (and mirror) are currently up at https://sfh.rooot.gay

the JSON API is pretty self-explanatory, currently there are 3 endpoints:
- `/api/v1/get_song/<id>` - `id` is the SFH internal id (_id); returns a single JSON object of the song
- `/api/v1/get_songs_for_level/<level_id>` - `<level_id>` being a gd level id
  - returns a JSON array of song objects
- `/api/v1/get_songs_with_id/<song_id>` - `<song_id>` being a NG/ingame song ID
  - returns a JSON array of song objects

a song object looks like this:

```json
{
    "id":"[INTERNAL SFH ID]",
    "name":"",
    "song_name":"[SONG DISPLAY NAME]",
    "song_id":"[SONG ID (ng, string because SFH has replacements for internal songs)]",
    "download_url":"[DIRECT LINK TO DOWNLOAD SONG]",
    "level_id":[OPTIONAL LEVEL ID]
}
```

The API is subject to change, breaking changes will have their API version increased (v1->v2, etc)

feel free to experiment around with the current API and infrastructure, let me know if you'd like anything changed (for convenience, etc) :3

i might implement a `/api/v1/get_all_songs` endpoint that returns data in the same format as SFH's `/songs` does.

**Comment by Fleeym** [comment]
Looks good. If you could include the "state" field that SFH has (tells me if the song is a mashup) it would be cool

**Comment by RoootTheFox** [comment]
@Fleeym state field added and changes deployed :3

**Comment by Fleeym** [comment]
Aight, this looks good, I'll see what I can cook up with it. I'll probably be able to dev more in the weekend.

**Comment by OM3GA6400** [comment]
we need this

**Comment by OM3GA6400** [comment]
@Fleeym are we getting this soon?

**Comment by Fleeym** [comment]
soon-ish. sorry, life is getting in the way at the moment and I have little time for modding :(

**Comment by RoootTheFox** [comment]
thank you for still considering this - just wanted to mention something: im pretty sure that the person who PR'd the mod API stuff (@FlafyDev) is working on [a separate mod that does something similar](https://github.com/FlafyDev/auto-nong) (as well as accumulating custom songs from other locations apart from SFH) which might be worth looking into.

**Comment by FlafyDev** [comment]
> thank you for still considering this - just wanted to mention something: the person who PR'd the mod API stuff (@FlafyDev) is working on [a separate mod that does something similar](https://github.com/FlafyDev/auto-nong) (as well as accumulating custom songs from other locations apart from SFH) which might be worth looking into.

Yep! Submitted the mod to the index https://github.com/geode-sdk/indexer/issues/1733 hoping to get it accepted

**Comment by Fleeym** [comment]
> thank you for still considering this - just wanted to mention something: the person who PR'd the mod API stuff (@FlafyDev) is working on [a separate mod that does something similar](https://github.com/FlafyDev/auto-nong) (as well as accumulating custom songs from other locations apart from SFH) which might be worth looking into.

Yep, I know about the mod, I can't integrate it into jukebox because of it using yt-dlp for downloads from youtube. Really cool addon to jukebox though. I like going the route of empowering the API and letting others go ham with ideas, as I myself don't have much time for modding these days.

**Comment by OM3GA6400** [comment]
if only this still existed ![Screenshot_20240406_162528_Opera.jpg](https://github.com/Fleeym/jukebox/assets/98067930/fb38fa7f-1c2c-4a58-a514-fd3fa88b9285)

**Comment by RoootTheFox** [comment]
just use Auto NONG at this point

**Comment by OM3GA6400** [comment]
> just use Auto NONG at this point

is there sfh integration?

**Comment by RoootTheFox** [comment]
> is there sfh integration?

yes, via my sfh mirror (sfh-rooot)

**Comment by Fleeym** [comment]
Closing since v3 added SFH support back
