### ISSUE TITLE
crash on opening file explorer to select nong

### ISSUE THREAD

**Issue by sphericle** [Fleeym/jukebox#47]
also an issue with other mods, must be a beta thing idk

crashlog: ([2024-06-16_20-35-23.txt](https://github.com/user-attachments/files/15860366/2024-06-16_20-35-23.txt))

2024-06-16T20:35:23-0400
Sorry :(

== Geode Information ==
- Working Directory: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash
- Loader Version: v3.0.0-beta.1 (Geometry Dash v2.206)
- Loader Commit: 057ffa5
- Bindings Commit: 48a3120
- Installed Mods: 21 (Loaded: 21/21)
- Problems: 0

== Exception Information ==
- Thread Information: "" (ID: 24492)
- Thread Start Address: ntdll.dll+0x35570 (RtlClearThreadWorkOnBehalfTicket+0x70)
- Exception Code: Unknown exception (0x6BA)
- Exception Address: KERNELBASE.dll+0x5F39C (RaiseException+0x6c)
- Exception Flags: 0x81
- Exception Parameters: 

== Stack Trace ==
- KERNELBASE.dll+0x5F39C (RaiseException+0x6c)
- RPCRT4.dll+0x49020 (RpcRaiseException+0x50)
- RPCRT4.dll+0x48FE4 (RpcRaiseException+0x14)
- RPCRT4.dll+0xD080A (NdrClientCall3+0x125a)
- RPCRT4.dll+0xCF69B (NdrClientCall3+0xeb)
- davclnt.dll+0x3831 (DllMain+0xe41)
- davclnt.dll+0x109E (NPOpenEnum+0x8e)
- MPR.dll+0x215C (WNetOpenEnumW+0xcfc)
- MPR.dll+0x1AEB (WNetOpenEnumW+0x68b)
- windows.storage.dll+0x5E5C35 (Ordinal2009+0x7ba5)
- windows.storage.dll+0x5E5B34 (Ordinal2009+0x7aa4)
- windows.storage.dll+0x270DFF (Ordinal2008+0x1d85f)
- windows.storage.dll+0x16FD48 (SHGetFileInfoW+0x4758)
- windows.storage.dll+0x16ECC2 (SHGetFileInfoW+0x36d2)
- windows.storage.dll+0x18F661 (SHGetNameFromIDList+0xd31)
- explorerframe.dll+0xFF1A (Ordinal130+0xff1a)
- explorerframe.dll+0x776E0 (Ordinal130+0x776e0)
- windows.storage.dll+0x17B696 (Ordinal2007+0xb76)
- windows.storage.dll+0x17B2A5 (Ordinal2007+0x785)
- windows.storage.dll+0x17B184 (Ordinal2007+0x664)
- SHCORE.dll+0x41540 (DllGetClassObject+0x630)
- ntdll.dll+0x4CEF1 (RtlQueueWorkItem+0x571)
- ntdll.dll+0x35E66 (RtlClearThreadWorkOnBehalfTicket+0x966)
- KERNEL32.DLL+0x1257D (BaseThreadInitThunk+0x1d)
- ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28)

== Register States ==
- RAX: 180CA0DD29 (-> 0x189A1EC17)
- RBX: 00000000 (0i | 0u)
- RCX: 00000048 (72i | 72u)
- RDX: 18900000001 (1687922147329i | 1u)
- RBP: 00000000 (0i | 0u)
- RSP: 180CA0FBA0 (&"")
- RDI: 00000000 (0i | 0u)
- RSI: 00000000 (0i | 0u)
- R8: 7FF9F7494DE6 (ntdll.dll+0x24DE6 (RtlImageNtHeaderEx+0x526))
- R9: 7FF9F74969C1 (ntdll.dll+0x269C1 (RtlAnsiStringToUnicodeString+0x1b61))
- R10: 00000025 (37i | 37u)
- R11: 00000000 (0i | 0u)
- R12: 00000000 (0i | 0u)
- R13: 00000000 (0i | 0u)
- R14: 00000000 (0i | 0u)
- R15: 00000000 (0i | 0u)
- RIP: 7FF9F74CAF28 (ntdll.dll+0x5AF28 (RtlUserThreadStart+0x28))
- XMM0: 0000000000380036 00007FF9F33F0100 (0 | 5.142863e-39 | 4.5908e-41 | -1.5132889e+31)
- XMM1: 000000180CA0DB80 00007FF901000044 (3.4e-44 | 2.478401e-31 | 4.5908e-41 | 2.3510078e-38)
- XMM2: 004F0044004E0049 0057005C003A0043 (7.2551e-39 | 7.163271e-39 | 7.989817e-39 | 5.326553e-39)
- XMM3: 0045005400530059 0053005C00530057 (6.336767e-39 | 7.622471e-39 | 7.622475e-39 | 7.622468e-39)
- XMM4: 006E00720065006B 005C00320033004D (1.0102064e-38 | 9.275535e-39 | 8.448936e-39 | 4.683718e-39)
- XMM5: 00007FF9F75059E1 00610062006C0065 (4.5908e-41 | -4.225862e+33 | 8.90818e-39 | 9.918375e-39)
- XMM6: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- XMM7: 0000000000000000 0000000000000000 (0 | 0 | 0 | 0)
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 1 
- SF: 0 | TF: 0 | ZF: 0 

== Installed Mods ==
x | [v1.1.8] adyagd.ingamelistmod
x | [v1.1.2] alphalaneous.shiftdeselect
x | [v1.1.2] alphalaneous.transparent_lists
x | [v1.1.2-beta.1] bitz.customprofiles
x | [v1.1.0] capeling.colored_level_info_bg
x | [v1.2.0] capeling.icon_profile
x | [v2.0.0-alpha.2] elnexreal.auto_high_priority
x | [v2.0.0-beta.10] elohmrow.death_tracker
x | [v0.2.0] flafy.autonong
x | [v2.10.0] fleym.nongd
x | [v1.3.0-alpha.13] gdutilsdevs.gdutils
x | [v1.6.0] geode.custom-keybinds
x | [v3.0.0-beta.1] geode.loader
x | [v1.12.0] geode.node-ids
x | [v1.2.0] hjfod.gmd-api
x | [v1.1.2] mat.run-info
x | [v1.4.2] prevter.bettercrash
x | [v4.0.0-beta] spaghettdev.betterinputs
x | [v2.3.1] thesillydoggo.gradientpages
x | [v1.4.4-beta.5] thesillydoggo.qolmod
x | [v1.2.1-beta.2] ziegenhainy.xxlify

== Stack Allocations ==
- 0x180CA0FBA0: 00000000 (0i | 0u)
- 0x180CA0FBA8: 00000000 (0i | 0u)
- 0x180CA0FBB0: 00000000 (0i | 0u)
- 0x180CA0FBB8: 00000000 (0i | 0u)
- 0x180CA0FBC0: 00000000 (0i | 0u)
- 0x180CA0FBC8: 00000000 (0i | 0u)
- 0x180CA0FBD0: 00000000 (0i | 0u)
- 0x180CA0FBD8: 00000000 (0i | 0u)
- 0x180CA0FBE0: 4F0FFFFFB30 (5433133628208i | 4294966064u)
- 0x180CA0FBE8: 4D0FFFFFB30 (5295694674736i | 4294966064u)
- 0x180CA0FBF0: 00000021 (33i | 33u)
- 0x180CA0FBF8: 00000000 (0i | 0u)
- 0x180CA0FC00: 00000000 (0i | 0u)
- 0x180CA0FC08: 00000000 (0i | 0u)
- 0x180CA0FC10: 00000000 (0i | 0u)
- 0x180CA0FC18: 00000000 (0i | 0u)
- 0x180CA0FC20: 00000000 (0i | 0u)
- 0x180CA0FC28: 00000000 (0i | 0u)
- 0x180CA0FC30: 00000000 (0i | 0u)
- 0x180CA0FC38: 00000000 (0i | 0u)
- 0x180CA0FC40: 00000000 (0i | 0u)
- 0x180CA0FC48: 00000000 (0i | 0u)
- 0x180CA0FC50: 00000000 (0i | 0u)
- 0x180CA0FC58: 00000000 (0i | 0u)
- 0x180CA0FC60: 00000000 (0i | 0u)
- 0x180CA0FC68: 00000000 (0i | 0u)
- 0x180CA0FC70: 00000000 (0i | 0u)
- 0x180CA0FC78: 00000000 (0i | 0u)
- 0x180CA0FC80: 00000000 (0i | 0u)
- 0x180CA0FC88: 00000000 (0i | 0u)
- 0x180CA0FC90: 00000000 (0i | 0u)
- 0x180CA0FC98: 00000000 (0i | 0u)

**Comment by Fleeym** [comment]
I've never seen this before... What Windows version are you on?

**Comment by Octostomp** [comment]
Also experiencing this. Using BetterCrashlogs it seems to be coming from this mod. 
[2024-06-01_11-05-24.txt](https://github.com/user-attachments/files/15865943/2024-06-01_11-05-24.txt)
[2024-06-16_11-16-41.txt](https://github.com/user-attachments/files/15865944/2024-06-16_11-16-41.txt)
[2024-06-16_11-20-30.txt](https://github.com/user-attachments/files/15865945/2024-06-16_11-20-30.txt)
[2024-06-16_11-25-42.txt](https://github.com/user-attachments/files/15865946/2024-06-16_11-25-42.txt)
[2024-06-16_11-28-02.txt](https://github.com/user-attachments/files/15865947/2024-06-16_11-28-02.txt)

**Comment by Fleeym** [comment]
Seems to be a false positive with the Geode crashlog handler. Will hopefully be fixed in beta 2

**Comment by Octostomp** [comment]
Beta-2 changed nothing :/

**Comment by Octostomp** [comment]
Neither did beta-5 :/

**Comment by Octostomp** [comment]
And the full release doesn't patch the bug either. OK opening an issue on geode

**Comment by sphericle** [comment]
closing since this is a geode issue probably i think
