### ISSUE TITLE
GD Crashes whenever you upload a song with an unknown symbol in it.

### ISSUE THREAD

**Issue by Gam3r404** [Fleeym/jukebox#51]
I was trying to add a media file (This media file contained "♭" inside of the name, which is why the game crashed), and once I uploaded it... I think I forgot to mention three times already that the game crashed. Instead of displaying a symbol with no display, the mod could just simply ignore the symbol like how GD does.

**Comment by Fleeym** [comment]
Closing since I didn't answer, sorry about that!

The fix is disabling `Autocomplete song metadata` in the mod settings.
