### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by iblowmymind** [Fleeym/jukebox#52]
Hello,
This is a mod I relied on Windows. Having switched to Mac, though, I noticed that the mod was absent from the index.
Does the mod currently work when compiled for Mac? Does it require additional code?
I'd be happy to be a tester if needed.
Thanks!

**Comment by Fleeym** [comment]
Hey there, mod isn't ported to mac as of now. It requires some reverse engineering of the game to find some missing addresses.

**Comment by iblowmymind** [comment]
Thank you for your quick reply! Please do let me know if I can be of any assistance.

**Comment by CoderMonkey1956** [comment]
> Hello, This is a mod I relied on Windows. Having switched to Mac, though, I noticed that the mod was absent from the index. Does the mod currently work when compiled for Mac? Does it require additional code? I'd be happy to be a tester if needed. Thanks!

You could try a vm as a temporary workaround, you could also replace files manually (the old NONG way)

**Comment by Fleeym** [comment]
As of v3, Jukebox is available on MacOS. Closing the thread.
