### ISSUE TITLE
Game Crashes when Adding Custom Nong

### ISSUE THREAD

**Issue by GDLsunq** [Fleeym/jukebox#54]
When I try to add a custom Nong to the game, it crashes when selecting the file without a Crash Report

**Comment by FlafyDev** [comment]
I've seen it can happen if megahack is enabled

Is that the case?

**Comment by GDLsunq** [comment]
Ye i have Megahack v8.0.1-alpha7 for gd 2.206

**Comment by GDLsunq** [comment]
MegaHack was the Problem without it, gd doesnt crash
