### ISSUE TITLE
[suggestion] menu to select individual songs to download from SFH

### ISSUE THREAD

**Issue by whitemaskedwolf** [Fleeym/jukebox#6]
suggesting this as the previous functionality which downloaded every song from sfh was removed because it was "way too much of a toll on their servers". adding a menu which displays a list of songs from the song file hub corresponding to the given song id and allowing the user to pick and download individual songs from the menu would not require any more bandwidth than navigating the website from the browser and downloading the songs from there, so i see this as a reasonable solution and in my opinion works better than simply downloading every song from the sfh anyways.

**Comment by Fleeym** [comment]
previous functionality did just that. the little spinning animation when selecting a song was there because it was downloading the song itself
