### ISSUE TITLE
Host download hangs at ~100%

### ISSUE THREAD

**Issue by sphericle** [Fleeym/jukebox#72]
Pasting a link to a nong seems to download normally, then the progress bar hangs at 100% ish (pictured)
![image](https://github.com/user-attachments/assets/3b91eab4-6981-49eb-a7b3-97e07d252324)

Tested using:
SFH
(https://api.songfilehub.com/song/64f54c6ceba5efcdadf78740?download=true&name=943100) 

and Discord's CDN 
(https://cdn.discordapp.com/attachments/855228426208935936/1314273328403451904/376.mp3?ex=67547d6b&is=67532beb&hm=d2623e9a2b005a4123038cb28445fcd1fcd27e2d403e6083178ad9dfe53c5663&)
^^ afaik links to discord's cdn have no auth so anyone should be able to access this link without being logged in / in the server

Level ID: 101511700

Hardware:
Windows 11
GD 2.207
Geode version 4.0.1

**Comment by madeline-yana** [comment]
Bumping, as I have the same issue.
Level ID: 52858977
Hosted file link: https://archive.kawaiizenbo.me/yanamusic/The%20Prodigy%20-%20Breathe.mp3

**Comment by Fleeym** [comment]
This will be fixed in the next update, you can try the latest beta: https://github.com/Fleeym/jukebox/releases/tag/v3.0.2-beta.3

**Comment by sphericle** [comment]
Sounds good 👍
