### ISSUE TITLE
Android 32 Crash When adding nong

### ISSUE THREAD

**Issue by ahmed4363** [Fleeym/jukebox#8]
Android 10 (32 bit) immediately crashes when attempting to add a song using Jukebox (the add button inside the song viewer after selecting mp3)
[Geode Crash.log](https://github.com/Fleeym/jukebox/files/14111692/Geode.Crashlog.log)

Is there a way to manually add songs for Jukebox in the geode files?

**Comment by Fleeym** [comment]
Github can't load the crashlog for me. Can you send it to me on discord? It's "fleeym"

**Comment by ahmed4363** [comment]
dont have discord but it beings up error code 13 in 2.4.0
