### ISSUE TITLE
Cannot open mp3 files

### ISSUE THREAD

**Issue by galadinowo** [Fleeym/jukebox#9]
(Android, 64-bit) When selecting an mp3 from the files, no matter which file is selected, an error popup comes up saying "Failed to open file".
![Screenshot_20240201_054929_Geode](https://github.com/Fleeym/jukebox/assets/140296207/c1c2256e-fdee-4645-a1a8-874d20413b05)

**Comment by Fleeym** [comment]
hey there, give media permissions to Geode in your phone settings

**Comment by galadinowo** [comment]
my only confusion is that android is supposed to ask for files access, but this just lets me choose a file? i can only control the permission if it asks for it, which it doesnt, i cant give the green light if android thinks it doesnt need it

**Comment by Fleeym** [comment]
requesting access is up to the app, i will add it in a future update
